### ISSUE TITLE
Fix scrolling issue of chat window

### ISSUE THREAD

**Issue by AshishKingdom** [AshishKingdom/chat-app#1]
When the number of message is large, the window does not scroll automatically to new messages.
One has to scroll manually to see the new messages.

**Comment by brandonmcconnell** [comment]
@AshishKingdom I'd like to take this one on!

**Comment by AshishKingdom** [comment]
@brandonmcconnell okay! I've assigned you this issue

**Comment by AshishKingdom** [comment]
This was fixed in PR #5
