### ISSUE TITLE
Color or Design Improvement of chat box

### ISSUE THREAD

**Issue by AshishKingdom** [AshishKingdom/chat-app#2]
The current design/color combination of chat window is not impressive. It needs to re-design again so that it is easy to read
messages

**Comment by KaranSinghBisht** [comment]
Hey, I would like to work on this

**Comment by neutr0ncodes** [comment]
Hey, @AshishKingdom Can I also give it a try?

**Comment by AshishKingdom** [comment]
@KaranSinghBisht @neutr0n420 yep! both of you can try working on this!
